name: "Slack Deployment Notification"
description: "Send eye-catching Slack message on deploy success/failure"
author: "chetanbothra"
branding:
  icon: "message-circle"
  color: "green"

inputs:
  slack_token:
    description: "Slack Bot Token"
    required: true
  slack_channel:
    description: "Slack Channel ID or name (e.g., #kananotification)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare Slack Message
      id: slack_message
      shell: bash
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          COLOR="good"
          STATUS_TEXT=":tada: *Deployment Successful!*"
        else
          COLOR="danger"
          STATUS_TEXT=":x: *Deployment Failed!*"
        fi

        cat <<EOF > slack_payload.json
        {
          "channel": "${{ inputs.slack_channel }}",
          "attachments": [
            {
              "color": "$COLOR",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "$STATUS_TEXT"
                  }
                },
                { "type": "divider" },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Repository:*\\n${{ github.repository }}" },
                    { "type": "mrkdwn", "text": "*Namespace:*\\n${{ github.event.inputs.namespace }}" },
                    { "type": "mrkdwn", "text": "*Commit:*\\n${{ github.sha }}" },
                    { "type": "mrkdwn", "text": "*Author:*\\n${{ github.actor }}" },
                    { "type": "mrkdwn", "text": "*Workflow:*\\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>" }
                  ]
                }
              ]
            }
          ]
        }
        EOF

    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v2
      with:
        token: ${{ inputs.slack_token }}
        method: chat.postMessage
        payload-file-path: ./slack_payload.json
